version: '3.8'

services:
  app:
    image: omkumar123/myimage
    ports:
        - 9091:9091
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CRUD?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: root
    depends_on:
        - db
  
  db:
    image: mysql:8.0.27
    environment:
        DATABASE_HOST: docker-mysql
        DATABASE_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: CRUD
        MYSQL_USER: admin
        MYSQL_PASSWORD: root